### ISSUE TITLE
Bot completely unresponsive

### ISSUE THREAD

**Issue by SodiumShine** [logicplace/TumbleWeed-Discord#1]
Currently I cannot get TumbleWeed to respond to any commands (e.g. tw!help or tw!nick). It did not generate the two roles TumbleWeed Admin and TumbleWeed Content provider. I have full Admin permissions on the server in question. I also tried kicking it and re-inviting, and giving the bot full admin permissions.

**Comment by logicplace** [comment]
I find it strange it won't respond to even tw!help but I'll take a look. In terms of creating the roles, I gave a special invite link in the ReadMe so that it would have the permissions upon joining, since that's when it creates them. Did you disable the permissions there? Is there a special TumbleWeed role that says "This role is automatically managed by an integration." ?

Recently, because I noticed that none of the servers its joined have had roles created (I assumed they were not using the link properly? since it has always worked fine for me), I added the ability for server owners and admins to be allowed command access regardless.

**Comment by logicplace** [comment]
Okay I figured it out I think. You may indeed need to kick the bot and reinvite it to create roles if it didn't just create them. Let me know.

**Comment by SodiumShine** [comment]
After kicking the bot and re-inviting it, the bot still did not generate the roles. 
Is there a period of time I should wait between kicking and re-inviting or does the bot need time to generate the roles?

However, the bot IS now responding to commands such as tw!help.

**Comment by logicplace** [comment]
I'm not sure about the admin permissions part but I found a bug I missed at least. It should hopefully work now.

**Comment by logicplace** [comment]
Okay so I've done some better debugging now that I've had time. It seems that most of the guilds this is connected to are returning the error "Maximum number of guild roles reached (250)" which is possibly why your roles are not being added.

I've added some robustness to managing the roles it adds, namely, it now detects if they were removed etc. This (along with some other bits) seems to have fixed at least the admin/owner permissions acting as TumbleWeed Admin. Note that this only works if the roles were not created.
